{{- if .Values.common.enableSecretCreation }}
  {{- $token := .Values.vaultConsul.vaultTokenBase64 }}
  {{- range .Values.common.commerceNameSpaces }}
apiVersion: v1
kind: Secret
metadata:
  name: vault-token-secret
  namespace: {{ . }}
type: Opaque
data:
  VAULT_TOKEN: {{ $token }}
---
  {{- end}}
{{- end}}