apiVersion: v1
kind: Service
metadata:
  name: vault-consul
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: vault-consul
spec:
  type: NodePort
  ports:
  - port: 8200
    name: port8200
  - port: 8500
    name: port8500
  selector:
    component: vault-consul
