## Default values for vault and consul for HCL Commerce V9

## Common configuration for all component docker 
common:
  ## tenant name used as the path name in vault secret
  tenant: demo

  ## a flag to enable ingress to easily access vault UI in development
  enableIngress: false
  ## external domain used in ingress domain when ingress is enabled
  externalDomain: mycompany.com
  ## a flag to enable secret creation in commerce namespaces
  enableSecretCreation: true
  ## namespaces where commerce environments are deployed
  ## it will create secret object of the vault token in each of these namespaces
  commerceNameSpaces:
    - commerce
  
  ## ingress controller [nginx,gke]
  ##   nginx - nginx ingress controller
  ##   gke - cloud load balancing using HTTP(S) Load Balancer in GKE
  ingressController: nginx

rbac:
  serviceAccountName: default

vaultConsul:
  ## docker image repository to pull consul and vault images 
  imageRepo: docker.io/
  ## consul docker image tag
  consulImageTag: 1.7.1
  ## vault docker image tag
  vaultImageTag: 1.3.3
  ## imagePullPolicy
  imagePullPolicy: IfNotPresent

  ## vault root token in UUID format. Please change it to your root token.
  vaultToken: 992d4a42-3796-d06e-c4f0-16nf8503877d
  ## vault root token in base 64 format
  ## Note: to encode the vault token in base64, do this: echo -n '<vault token plain text>' | base64
  ##       the -n is required to trim the trailing newline character
  vaultTokenBase64: OTkyZDRhNDItMzc5Ni1kMDZlLWM0ZjAtMTZuZjg1MDM4Nzdk
  ## a flag to enable data loading
  vaultLoadData: true
  ## data to load to vault under mounted <tenant> secret
  ## Format:
  ##  <environment1>:
  ##    <auth | live | both>: # properties under 'both' are created under the environment level, otherwise are created under environment type (auth | live) level
  ##      <name1>:<value1>
  ##      <name2>:<value2>
  ##      ...
  ##  <environment2>:
  ##    <auth | live>:
  ##      <name1>:<value1>
  ##      <name2>:<value2>
  ##
  ## Note: 
  ##       1. the default database values are based on the db docker images shipped with commerce
  ##       2. the default dbHost values are configured assuming using the db docker image deployed in the same K8s cluster in 'commerce' name space.
  ##       3. the following data covers 2 environments (dev and qa)
  ##       4. please modify the values based on your deployment sepcificiation
  vaultData:
    dev:
      auth:
        dbHost: "demodevauthdb.commerce.svc.cluster.local"
        dbName: "mall"
        dbUser: "wcs"
        dbPassword: "wcs1"
        dbType: "db2"
        dbPort: "50000"
        dbaUser: "db2inst1"
        dbaPassword: "diet4coke"
        dbPassEncrypt: "okFQawPB19Tkl1wKqQPDdAVtwz+mIgpJyqJQUuUWtyk="
        dbaPassEncrypt: "u4h5LS/vJeSzsCfnt6NGfGHYPWK2fRq0+djkmB/iNWU="
        toolingBaseUrl: "https://cmc.demodevauth.mycompany.com/tooling"
      live:
        dbHost: "demodevlivedb.commerce.svc.cluster.local"
        dbName: "mall"
        dbUser: "wcs"
        dbPassword: "wcs1"
        dbType: "db2"
        dbPort: "50000"
        dbaUser: "db2inst1"
        dbaPassword: "diet4coke"
        dbPassEncrypt: "okFQawPB19Tkl1wKqQPDdAVtwz+mIgpJyqJQUuUWtyk="
        dbaPassEncrypt: "u4h5LS/vJeSzsCfnt6NGfGHYPWK2fRq0+djkmB/iNWU="
        toolingBaseUrl: "https://cmc.demodevlive.mycompany.com/tooling"
      both:
        domainName: "commerce.svc.cluster.local"
        authJWKS: "{base64}eyJrZXlzIjpbeyJrdHkiOiJSU0EiLCJraWQiOiJkZW1vS2V5IiwibiI6ImpIckkzcDRTQ1FUVUNuQmhaWkhESllzd1dCTXVhd3B5VkM2RGFLZENZeDc1MXdtRmx0bGlqY1VyOEd1WkMyLXZvMTZzT2RKZ0J5MDRwdmxydDRTc0ZDeVJvcmU1cVRyZTZJdTZfZTZ4dGRobHg1XzIzaVNmY1pqaG5tTk1SV2pFUC1wbmpZQXlWbjBINU10YVoyLXJlcDlxOUQyRENSQS15ZEtaLTZVd2t0VFZhRy1kTHNuLUNKMVNTNDQydkdybnJWYXU0b25RaVRSQlFjM2NkdHFzdDEzU3BvVHN1Y0lKblJ4RnNtUHd4M0NFUk1CTURwWi0weGRJVHJZNXVUZ3JvZnpRY21VcDRsVFZDQk9vRElJM3AyOE52YWt0TFNTWG00VmFfaHVZQlRlellwU21YWXRpTkpuY2FsUFRnREVaTkNSOWJLdXVQMjZUczMycnUtaGdnUSIsImUiOiJBUUFCIiwiZCI6ImpDZGdTc0o0Q2VsNFItWHhOaTJqX2N3TmNvSEltT0MyU2dpUjhKS1hLRjlhTWxGOHA1REF3LUxJd0xnSTNDRVVvYkN0c1k2VFlmV2JCUFBwcFJISHdPVHFjLVpMWkd5b3dtZk9LdFNfRmtjTTNJcGEtU3llcXU0MWd4bGNtZzg1Wk85UFd4eGduR3RudWJ1c3VXX3ZMSXJxWVQwUmc3UmlnR2NPVzhObVg4WlVYZTJJbDEzZi00VmVWWGRFZEE3YngwTDNkWE9HTzFCSDZJMGNGWmZIU2RYLWl1dzBiZWQ4ZUY0ODNIeDRkY3RMRkJCWmk0eC1iaWNCeEMxSDZLa2tRaThONXV4LVJVWUt0U2NzMFlzVUd3aTkwVjdBanRfY0JnckpZMGZuQk1iQUtfYzVKa0RfM09HYmw1cTZjYlBLQ2lxWDNpZi1hdEV6REkzQXM1T1hBUSIsInAiOiI4ZzRUZWliMUxoblA4NWVFZF9NYjhEcnhFV0hwNjFkTmhodEdEWHhBSGRvWk45aVJNZk00QUxvMG5uNGNwTllVcXpWY3ZmZy1KVHJ3eDJyb1dYRDZGVzlXRXJyWi1HUVpDM0dVRXgyYXRybW4wRUFFM3dhWGI1RXN5X0tfMDFjZFVDbmREU055ZGtSU1FIRTB3Z3F1QV9uTWkxV3RKS3ViVXp4NW9fQ0xJMUUiLCJxIjoibEpLaWJma2lyWU1hZmxiZEw1V0VHdlE0Y2lPaER6TFd4WVBQejlCa3pFWGdCaGxTY0VsLVhLQnh2bTFBa2dkdkhZMXVlT3IxdUhCeXBlSnhCbTNOTUtfelZjOUd5X1NUUnpabkJIajZERGZURVoybW5aWEhXSGNCMTNjQi1XcUh3c2xlaHBLZF9FOE9Db3NnM25rQjZVdDVhc3h4cy03X2FhV05yYnJwUGpFIiwiZHAiOiJwMGM1Q0tMaHItRmd4X3ZfTFJJU1RidS1HNEFxTTF6YkU0SEhzTXdjVjBVQlJvbmhGYjc3QmUycExac0QycHFrSUFtNXRRTllsMHdiV0FVMjI1RHJFMk1rX2I2cG9qSXk2S2l1WjJOX0p5WTRwZi1JSGtVazVKSlVmZ0dkdGNVdldkWUVrTzdkVElROHY1SThucGpZMTZDTFRnT0FxNlg0cXRaUlRnMlBhbkUiLCJkcSI6IlZKeUpxbzJtcFNBejExMkt5ODJmbFdZZU8wcDFMOTJwR0lVdnRVOGVDSU9HeUpKbE01TjNSak1OZEFCdU5Idk5XUXd4ck9WS21RWlpGSVc0RG93N3ZnMkdUQWttYllMVTJVcHZNc25leFZTSmZNX0drcG81RV9WNmRBWFBkd2FuV0ZRcjVBSGR2VkljVWY3WDhqc0J6cVh2LU5XRHI1QmRud0hzaE5NY2dCRSIsInFpIjoiTjdoWERqcEVCZTQxRFp0LUJCelZ4THBOSnd5ckZwSnZqZTFKVGNndkRld0Q5NDVTWWVROGROWGpsYWlVYjVYU19JWWg1dXdjM1lMOGxNeWdGUm1kNVR1c2xDcmU2VUxleGZBY1p0Q3dlVkl0WEsxdjBCUlVKSHFzRU1PZVNGdE12VU5Wdk5sRzlKbmd0OWMxTjRELWZNaVR3VkZndTBIOUFDY1RXT2VYYzZjIn1dfQ=="
        elasticSearchHost: elasticsearch-master.elastic.svc.cluster.local
        elasticSearchPort: 9200
        elasticSearchScheme: http
        nifiWebHttpPort: 30600
        nifiClusterIsNode: false
        nifiClusterNodeProtocalPort: 30600
        zookeeperHost: my-zookeeper.zookeeper.svc.cluster.local
        zookeeperPort: 2181
        nifiElectionMaxWait: "1 min"
        nifiJvmHeapInit: 4096m
        nifiJvmHeapMax: 6144m
        registryHost: demodevregistry-app.commerce.svc.cluster.local
        registryPort: 30400
        nifiHost: demodevnifi-app.commerce.svc.cluster.local
        nifiPort: 30800
        redisHost: my-redis-master.redis.svc.cluster.local
        redisPort: 6379
    qa:
      auth:
        dbHost: "demoqaauthdb.commerce.svc.cluster.local"
        dbName: "mall"
        dbUser: "wcs"
        dbPassword: "wcs1"
        dbType: "db2"
        dbPort: "50000"
        dbaUser: "db2inst1"
        dbaPassword: "diet4coke"
        dbPassEncrypt: "okFQawPB19Tkl1wKqQPDdAVtwz+mIgpJyqJQUuUWtyk="
        dbaPassEncrypt: "u4h5LS/vJeSzsCfnt6NGfGHYPWK2fRq0+djkmB/iNWU="
        toolingBaseUrl: "https://cmc.demoqaauth.mycompany.com/tooling"
      live:
        dbHost: "demoqalivedb.commerce.svc.cluster.local"
        dbName: "mall"
        dbUser: "wcs"
        dbPassword: "wcs1"
        dbType: "db2"
        dbPort: "50000"
        dbaUser: "db2inst1"
        dbaPassword: "diet4coke"
        dbPassEncrypt: "okFQawPB19Tkl1wKqQPDdAVtwz+mIgpJyqJQUuUWtyk="
        dbaPassEncrypt: "u4h5LS/vJeSzsCfnt6NGfGHYPWK2fRq0+djkmB/iNWU="
        toolingBaseUrl: "https://cmc.demoqalive.mycompany.com/tooling"
      both:
        domainName: "commerce.svc.cluster.local"
        authJWKS: "{base64}eyJrZXlzIjpbeyJrdHkiOiJSU0EiLCJraWQiOiJkZW1vS2V5IiwibiI6ImpIckkzcDRTQ1FUVUNuQmhaWkhESllzd1dCTXVhd3B5VkM2RGFLZENZeDc1MXdtRmx0bGlqY1VyOEd1WkMyLXZvMTZzT2RKZ0J5MDRwdmxydDRTc0ZDeVJvcmU1cVRyZTZJdTZfZTZ4dGRobHg1XzIzaVNmY1pqaG5tTk1SV2pFUC1wbmpZQXlWbjBINU10YVoyLXJlcDlxOUQyRENSQS15ZEtaLTZVd2t0VFZhRy1kTHNuLUNKMVNTNDQydkdybnJWYXU0b25RaVRSQlFjM2NkdHFzdDEzU3BvVHN1Y0lKblJ4RnNtUHd4M0NFUk1CTURwWi0weGRJVHJZNXVUZ3JvZnpRY21VcDRsVFZDQk9vRElJM3AyOE52YWt0TFNTWG00VmFfaHVZQlRlellwU21YWXRpTkpuY2FsUFRnREVaTkNSOWJLdXVQMjZUczMycnUtaGdnUSIsImUiOiJBUUFCIiwiZCI6ImpDZGdTc0o0Q2VsNFItWHhOaTJqX2N3TmNvSEltT0MyU2dpUjhKS1hLRjlhTWxGOHA1REF3LUxJd0xnSTNDRVVvYkN0c1k2VFlmV2JCUFBwcFJISHdPVHFjLVpMWkd5b3dtZk9LdFNfRmtjTTNJcGEtU3llcXU0MWd4bGNtZzg1Wk85UFd4eGduR3RudWJ1c3VXX3ZMSXJxWVQwUmc3UmlnR2NPVzhObVg4WlVYZTJJbDEzZi00VmVWWGRFZEE3YngwTDNkWE9HTzFCSDZJMGNGWmZIU2RYLWl1dzBiZWQ4ZUY0ODNIeDRkY3RMRkJCWmk0eC1iaWNCeEMxSDZLa2tRaThONXV4LVJVWUt0U2NzMFlzVUd3aTkwVjdBanRfY0JnckpZMGZuQk1iQUtfYzVKa0RfM09HYmw1cTZjYlBLQ2lxWDNpZi1hdEV6REkzQXM1T1hBUSIsInAiOiI4ZzRUZWliMUxoblA4NWVFZF9NYjhEcnhFV0hwNjFkTmhodEdEWHhBSGRvWk45aVJNZk00QUxvMG5uNGNwTllVcXpWY3ZmZy1KVHJ3eDJyb1dYRDZGVzlXRXJyWi1HUVpDM0dVRXgyYXRybW4wRUFFM3dhWGI1RXN5X0tfMDFjZFVDbmREU055ZGtSU1FIRTB3Z3F1QV9uTWkxV3RKS3ViVXp4NW9fQ0xJMUUiLCJxIjoibEpLaWJma2lyWU1hZmxiZEw1V0VHdlE0Y2lPaER6TFd4WVBQejlCa3pFWGdCaGxTY0VsLVhLQnh2bTFBa2dkdkhZMXVlT3IxdUhCeXBlSnhCbTNOTUtfelZjOUd5X1NUUnpabkJIajZERGZURVoybW5aWEhXSGNCMTNjQi1XcUh3c2xlaHBLZF9FOE9Db3NnM25rQjZVdDVhc3h4cy03X2FhV05yYnJwUGpFIiwiZHAiOiJwMGM1Q0tMaHItRmd4X3ZfTFJJU1RidS1HNEFxTTF6YkU0SEhzTXdjVjBVQlJvbmhGYjc3QmUycExac0QycHFrSUFtNXRRTllsMHdiV0FVMjI1RHJFMk1rX2I2cG9qSXk2S2l1WjJOX0p5WTRwZi1JSGtVazVKSlVmZ0dkdGNVdldkWUVrTzdkVElROHY1SThucGpZMTZDTFRnT0FxNlg0cXRaUlRnMlBhbkUiLCJkcSI6IlZKeUpxbzJtcFNBejExMkt5ODJmbFdZZU8wcDFMOTJwR0lVdnRVOGVDSU9HeUpKbE01TjNSak1OZEFCdU5Idk5XUXd4ck9WS21RWlpGSVc0RG93N3ZnMkdUQWttYllMVTJVcHZNc25leFZTSmZNX0drcG81RV9WNmRBWFBkd2FuV0ZRcjVBSGR2VkljVWY3WDhqc0J6cVh2LU5XRHI1QmRud0hzaE5NY2dCRSIsInFpIjoiTjdoWERqcEVCZTQxRFp0LUJCelZ4THBOSnd5ckZwSnZqZTFKVGNndkRld0Q5NDVTWWVROGROWGpsYWlVYjVYU19JWWg1dXdjM1lMOGxNeWdGUm1kNVR1c2xDcmU2VUxleGZBY1p0Q3dlVkl0WEsxdjBCUlVKSHFzRU1PZVNGdE12VU5Wdk5sRzlKbmd0OWMxTjRELWZNaVR3VkZndTBIOUFDY1RXT2VYYzZjIn1dfQ=="
        elasticSearchHost: elasticsearch-master.elastic.svc.cluster.local
        elasticSearchPort: 9200
        elasticSearchScheme: http
        zookeeperHost: my-zookeeper.zookeeper.svc.cluster.local
        zookeeperPort: 2181
        nifiJvmHeapInit: 4096m
        nifiJvmHeapMax: 6144m
        redisHost: my-redis-master.redis.svc.cluster.local
        redisPort: 6379

  
test:
  image: docker.io/centos:latest